name: mini_ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-266.0.dev

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.6.3
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.3
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  riverpod_generator: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
