name: mini_ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-266.0.dev

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.6.3
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.3
  dio: ^5.7.0
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  email_validator: '^2.1.17'
  water_drop_nav_bar: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
